In [17]:
import pandas as pd
import numpy as np
from numpy import random
import unicodedata

In [47]:
df = pd.read_csv("./palavras.txt", header=None, names=["palavras"])
df

        palavras
0              a
1              à
2          Aarão
3            aba
4        abacate
...          ...
261783  zurremos
261784    zurres
261785     zurro
261786    zurros
261787    zurrou

[261788 rows x 1 columns]

In [49]:
def normalizar_palavras(palavra_normalizada): 
    return unicodedata.normalize('NFKD', palavra_normalizada).encode('ASCII', 'ignore').decode('utf-8').upper()
        
df['palavras'] = df['palavras'].apply(normalizar_palavras)

df

        palavras
0              A
1              A
2          AARAO
3            ABA
4        ABACATE
...          ...
261783  ZURREMOS
261784    ZURRES
261785     ZURRO
261786    ZURROS
261787    ZURROU

[261788 rows x 1 columns]

In [ ]:
df.to_csv("./palavras_normalizadas.csv", index=False, header=False)

In [32]:
def gerar_matriz():
    matriz = np.full((8, 8), ' ') # 64 espaços 
    x = random.randint(14)
    print("numero de X: ", x)
    for x in range(x): 
        coluna = random.randint(0, 8)
        linha = random.randint(0, 8)
        matriz[linha, coluna] = 'X'
    return matriz

In [33]:
gerar_matriz()

numero de X:  9

array([[' ', ' ', 'X', ' ', ' ', 'X', ' ', ' '],
       [' ', ' ', ' ', 'X', ' ', ' ', ' ', ' '],
       ['X', 'X', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'X', 'X', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', 'X', ' ', ' ', ' ']], dtype='<U1')